# Generated by Django 6.0.7 on 2026-08-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_add_mandate_details_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tag',
        ),
    ]
