# Generated by Django 6.0.7 on 2026-08-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Cousin', 'Cousin'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Father', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('aadhar', models.CharField(blank=True, default='', max_length=20)),
                ('height_weight', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='contacts.contact')),
            ],
        ),
    ]
