# Generated by Django 6.0.7 on 2026-08-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('aadhar', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='contacts.contact')),
            ],
        ),
    ]
