# Generated by Django 6.0.7 on 2026-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='aadhar_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pan_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/pan/'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='aadhar_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/family/aadhar/'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='pan_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/family/pan/'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='aadhar_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/nominees/aadhar/'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='pan_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/nominees/pan/'),
        ),
    ]
