# Generated by Django 6.0.7 on 2026-08-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_contact_aadhar_doc_contact_pan_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('BSE', 'BSE Mandate'), ('CAMS', 'CAMS Mandate'), ('KFIN', 'KFIN Mandate'), ('NSE', 'NSE Mandate'), ('Other', 'Other Mandate')], default='BSE', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('mandate_id', models.CharField(blank=True, default='', max_length=50)),
                ('mandate_limit', models.CharField(blank=True, default='', max_length=50)),
                ('payer_name', models.CharField(blank=True, default='', max_length=100)),
                ('umrn', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='contacts.contact')),
            ],
        ),
    ]
