# Generated by Django 6.0.7 on 2026-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='price',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='process_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='stamp_duty',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='transaction_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='units',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
